name: Build Plugin

on:
  push:
    branches: [ master, fix-pipelines ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: buildPlugin
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
    - name: Install .NET dependencies
      run: dotnet restore
    - name: Build plugin
      env:
        SPECFLOW_TELEMETRY_ENABLED: 0
      run: gradle :buildPlugin --stacktrace -PintellijPublishToken=none
    - name: dotnet-tests-report
      uses: zyborg/dotnet-tests-report@v1.4.3
      env:
        SPECFLOW_TELEMETRY_ENABLED: 0
      with:
        report_name: plugin_tests
        report_title: Plugin Tests
        set_check_status_from_test_outcome: true
        project_path: src/dotnet/ReSharperPlugin.SpecflowRiderPlugin.Tests/ReSharperPlugin.SpecflowRiderPlugin.Tests.csproj
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Prevent githubs matrjoschka effect
      run: unzip output/specflowriderplugin-*.zip -d "./artifactz/"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SpecFlowPlugin
        path: artifactz
